# Generated by Django 4.2.6 on 2023-10-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categor',
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
    ]
