# Generated by Django 4.2.6 on 2023-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_categor_alter_shop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='photo_path',
            field=models.ImageField(default='2144250001_2_1_16.png', upload_to='photo/%Y/%M/%D/', verbose_name='Картинка '),
        ),
    ]
