# Generated by Django 4.2.6 on 2023-10-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description1',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
