# Generated by Django 4.2.5 on 2023-10-29 01:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_photo_path1_shop_photo_path2_shop_photo_path3'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shop',
            managers=[
                ('Category', django.db.models.manager.Manager()),
            ],
        ),
    ]
