# Generated by Django 4.2.5 on 2023-10-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shop_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shop',
            managers=[
            ],
        ),
    ]
