# Generated by Django 4.2.6 on 2023-10-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shop_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(db_index=True, max_length=60, verbose_name='Категория')),
            ],
        ),
    ]
