# Generated by Django 4.2.5 on 2023-10-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
